// Generated by Copilot
// Jest configuration for React component testing
module.exports = {
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.ts'],
  moduleNameMapper: {
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
  },
  transform: {
    '^.+\\.(ts|tsx)$': ['ts-jest', {
      tsconfig: 'tsconfig.jest.json'
    }],
  },
  testMatch: [
    '<rootDir>/jest-tests/components/**/*.(test|spec).(ts|tsx)',
    '<rootDir>/jest-tests/logging/**/*.(test|spec).(ts|tsx)'
  ],
  testPathIgnorePatterns: [
    '<rootDir>/tests/storeUX.spec.ts',
    '<rootDir>/tests/types.spec.ts',
    '<rootDir>/tests-examples/',
    '<rootDir>/node_modules/'
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json']
};
