// Generated by Copilot  
// Contract test for FakeStore API - Story 1.5.7: API Contract Validation
// Run separately with: npm run test -- ApiContract.test.ts
import axios from 'axios';
import { testProducts } from '../../tests/productsData';

describe('FakeStore API Contract Tests - Story 1.5.7', () => {
    describe('Test 1.5.7: Real API structure matches mock data schema', () => {
        test('validates /products endpoint structure and sample data', async () => {
            // Given: FakeStore API is available and our mock data exists
            // When: I fetch real API data and compare with mock schema
            // Then: The structure should match and key products should exist

            console.log('🔍 Testing FakeStore API contract...');
            
            try {
                // Fetch real API data
                const response = await axios.get('https://fakestoreapi.com/products');
                const realProducts = response.data;

                console.log(`✅ API responded with ${realProducts.length} products`);
                
                // Validate response structure
                expect(Array.isArray(realProducts)).toBe(true);
                expect(realProducts.length).toBeGreaterThan(0);
                
                // Validate we have the expected number of products (should be ~20)
                expect(realProducts.length).toBeGreaterThanOrEqual(15);
                expect(realProducts.length).toBeLessThanOrEqual(25);
                
                // Check structure of first product matches our schema
                const firstProduct = realProducts[0];
                expect(firstProduct).toHaveProperty('id');
                expect(firstProduct).toHaveProperty('title');
                expect(firstProduct).toHaveProperty('price');
                expect(firstProduct).toHaveProperty('description');
                expect(firstProduct).toHaveProperty('category');
                expect(firstProduct).toHaveProperty('image');
                expect(firstProduct).toHaveProperty('rating');
                
                // Validate rating object structure
                expect(firstProduct.rating).toHaveProperty('rate');
                expect(firstProduct.rating).toHaveProperty('count');
                
                // Type validation
                expect(typeof firstProduct.id).toBe('number');
                expect(typeof firstProduct.title).toBe('string');
                expect(typeof firstProduct.price).toBe('number');
                expect(typeof firstProduct.description).toBe('string');
                expect(typeof firstProduct.category).toBe('string');
                expect(typeof firstProduct.image).toBe('string');
                expect(typeof firstProduct.rating.rate).toBe('number');
                expect(typeof firstProduct.rating.count).toBe('number');
                
                // Validate a few known products exist (from our test data)
                const fjallravenBackpack = realProducts.find((p: any) => 
                    p.title === 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops'
                );
                expect(fjallravenBackpack).toBeDefined();
                if (fjallravenBackpack) {
                    expect(fjallravenBackpack.id).toBe(1);
                    expect(fjallravenBackpack.category).toBe("men's clothing");
                }
                
                const danvouyShirt = realProducts.find((p: any) => 
                    p.title === 'DANVOUY Womens T Shirt Casual Cotton Short'
                );
                expect(danvouyShirt).toBeDefined();
                if (danvouyShirt) {
                    expect(danvouyShirt.id).toBe(20);
                    expect(danvouyShirt.category).toBe("women's clothing");
                }
                
                console.log('✅ Contract test passed - API structure matches mock data');
                
            } catch (error) {
                console.error('❌ Contract test failed:', error.message);
                
                if (error.code === 'ENOTFOUND' || error.code === 'ECONNREFUSED') {
                    console.log('🚨 FakeStore API appears to be down - this is expected occasionally');
                    console.log('📝 This test failure does not block development');
                    // Still fail the test but with context
                    throw new Error(`FakeStore API unavailable: ${error.message}`);
                }
                
                throw error;
            }
        }, 10000); // 10 second timeout for API calls
    });
});
