// Generated by Copilot
// Tests for SimpleProductList React component
import '@testing-library/jest-dom';
import React from 'react';
import { render, screen } from '@testing-library/react';
import { SimpleProductList } from '../../src/components/SimpleProductList';
import { Product } from '../../src/domain/Product';

describe('SimpleProductList', () => {
  const mockProduct1: Product = {
    id: 1,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
    price: 109.95,
    description: 'Your perfect pack for everyday use and walks in the forest.',
    category: 'men\'s clothing',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg'
  };

  const mockProduct2: Product = {
    id: 2,
    title: 'DANVOUY Womens T Shirt Casual Cotton Short',
    price: 12.99,
    description: '95%Cotton,5%Spandex, Features: Casual, Short Sleeve',
    category: 'women\'s clothing', 
    image: 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg'
  };

  const mockProducts: Product[] = [mockProduct1, mockProduct2];

  test('renders loading state when productsOrError is null', () => {
    render(<ul><SimpleProductList productsOrError={null} /></ul>);
    
    expect(screen.getByText('Loading products...')).toBeInTheDocument();
  });

  test('renders error state when productsOrError is an Error', () => {
    const error = new Error('Network error');
    render(<ul><SimpleProductList productsOrError={error} /></ul>);
    
    expect(screen.getByText('Failed to fetch products')).toBeInTheDocument();
  });

  test('renders empty state when productsOrError is an empty array', () => {
    render(<ul><SimpleProductList productsOrError={[]} /></ul>);
    
    expect(screen.getByText('No products available. Please come back soon!')).toBeInTheDocument();
  });

  test('renders product list when productsOrError contains products', () => {
    render(<ul><SimpleProductList productsOrError={mockProducts} /></ul>);
    
    // Check that both products are rendered
    expect(screen.getByText('Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops - $109.95')).toBeInTheDocument();
    expect(screen.getByText('DANVOUY Womens T Shirt Casual Cotton Short - $12.99')).toBeInTheDocument();
    
    // Check that we have the correct number of list items
    const listItems = screen.getAllByRole('listitem');
    expect(listItems).toHaveLength(2);
  });

  test('renders single product correctly', () => {
    render(<ul><SimpleProductList productsOrError={[mockProduct1]} /></ul>);
    
    expect(screen.getByText('Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops - $109.95')).toBeInTheDocument();
    
    const listItems = screen.getAllByRole('listitem');
    expect(listItems).toHaveLength(1);
  });

  test('product items have correct structure and content', () => {
    render(<ul><SimpleProductList productsOrError={mockProducts} /></ul>);
    
    const listItems = screen.getAllByRole('listitem');
    
    // First product
    expect(listItems[0]).toHaveTextContent('Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops - $109.95');
    
    // Second product
    expect(listItems[1]).toHaveTextContent('DANVOUY Womens T Shirt Casual Cotton Short - $12.99');
  });

  test('matches vanilla DOM output format exactly', () => {
    // This test ensures our React component produces the same output as the vanilla implementation:
    // products.map((product) => `<li>${product.title} - $${product.price}</li>`)
    
    render(<ul><SimpleProductList productsOrError={[mockProduct1]} /></ul>);
    
    const listItem = screen.getByRole('listitem');
    expect(listItem).toHaveTextContent('Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops - $109.95');
    expect(listItem.tagName.toLowerCase()).toBe('li');
  });
});
