import React from 'react';

// Generated by Copilot
// Basic Header component - Story 1: Minimal implementation to pass Test 1.1
export const Header: React.FC = () => {
    return (
        <div>Header</div>
    );
};
