import React from 'react';

// Generated by Copilot
// Professional Header component - Story 1: E-commerce header with site title
export const Header: React.FC = () => {
    return (
        <header style={{
            backgroundColor: '#2c3e50',
            color: 'white',
            padding: '1rem 2rem',
            boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
            marginBottom: '1rem'
        }}>
            <div style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                maxWidth: '1200px',
                margin: '0 auto'
            }}>
                <h1 style={{
                    margin: 0,
                    fontSize: '1.8rem',
                    fontWeight: 'bold'
                }}>
                    OurFakeStore
                </h1>
                <div style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '2rem'
                }}>
                    <nav>
                        <ul style={{
                            display: 'flex',
                            listStyle: 'none',
                            margin: 0,
                            padding: 0,
                            gap: '1.5rem'
                        }}>
                            <li><a href="#" style={{ color: 'white', textDecoration: 'none' }}>Home</a></li>
                            <li><a href="#" style={{ color: 'white', textDecoration: 'none' }}>Products</a></li>
                            <li><a href="#" style={{ color: 'white', textDecoration: 'none' }}>Categories</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
    );
};
