// Generated by Copilot
import React from 'react';
import { Product } from '../domain/Product';

interface ProductListProps {
    products: Product[];
    isLoading: boolean;
    error: Error | null;
}

export const ProductList: React.FC<ProductListProps> = ({ products, isLoading, error }) => {
    if (isLoading) {
        return (
            <div className="d-flex justify-content-center">
                <div className="spinner-border" role="status">
                    <span className="visually-hidden">Loading...</span>
                </div>
            </div>
        );
    }

    if (error) {
        return (
            <div className="alert alert-danger" role="alert">
                <i className="bi bi-exclamation-triangle"></i> Failed to fetch products
            </div>
        );
    }

    if (products.length === 0) {
        return (
            <div className="alert alert-info" role="alert">
                <i className="bi bi-info-circle"></i> No products available. Please come back soon!
            </div>
        );
    }

    return (
        <ul id="product-list" className="list-group">
            {products.map((product) => (
                <li key={product.id} className="list-group-item d-flex justify-content-between align-items-center">
                    <div>
                        <h6 className="mb-1">{product.title}</h6>
                        <small className="text-muted">{product.category}</small>
                    </div>
                    <span className="badge bg-primary rounded-pill">${product.price}</span>
                </li>
            ))}
        </ul>
    );
};
