// Generated by Copilot
import React from 'react';
import { Product } from '../domain/Product';

interface ProductListProps {
    products: Product[];
    isLoading: boolean;
    error: Error | null;
}

export const ProductList: React.FC<ProductListProps> = ({ products, isLoading, error }) => {
    if (isLoading) {
        return (
            <div className="d-flex justify-content-center">
                <div className="spinner-border" role="status">
                    <span className="visually-hidden">Loading...</span>
                </div>
            </div>
        );
    }

    if (error) {
        return (
            <div className="alert alert-danger" role="alert">
                <i className="bi bi-exclamation-triangle"></i> Failed to fetch products
            </div>
        );
    }

    if (products.length === 0) {
        return (
            <div className="alert alert-info" role="alert">
                <i className="bi bi-info-circle"></i> No products available. Please come back soon!
            </div>
        );
    }

    return (
        <div className="row">
            {products.map((product) => (
                <div key={product.id} className="col-md-4 mb-4">
                    <div data-testid="product-card" className="card h-100">
                        <img src={product.image} alt={product.title} className="card-img-top" style={{height: '200px', objectFit: 'cover'}} />
                        <div className="card-body">
                            <h5 className="card-title">{product.title}</h5>
                            <p className="card-text">{product.category}</p>
                            <p className="card-text text-primary fw-bold">${product.price}</p>
                        </div>
                    </div>
                </div>
            ))}
        </div>
    );
};
