import React from 'react';
import { Product } from '../domain/Product';

// Generated by Copilot
// Simple ProductList component that matches the vanilla DOM implementation exactly
interface SimpleProductListProps {
    productsOrError: Product[] | Error | null;
}

export const SimpleProductList: React.FC<SimpleProductListProps> = ({ productsOrError }) => {
    // Handle error case - matches vanilla: productList!.innerHTML = "<li>Failed to fetch products</li>";
    if (productsOrError instanceof Error) {
        return <li>Failed to fetch products</li>;
    }

    // Handle null/loading case  
    if (!productsOrError) {
        return <li>Loading products...</li>;
    }

    // Handle empty products case - matches vanilla: productList!.innerHTML = "<li>No products available. Please come back soon!</li>";
    if (productsOrError.length === 0) {
        return <li>No products available. Please come back soon!</li>;
    }

    // Handle normal case with products - matches vanilla: products.map((product) => `<li>${product.title} - $${product.price}</li>`)
    return (
        <>
            {productsOrError.map((product) => (
                <li key={product.id}>
                    {product.title} - ${product.price}
                </li>
            ))}
        </>
    );
};
