#!/usr/bin/env node
// Generated by Copilot
// Test runner script that executes all tests with formatted output

const { execSync } = require('child_process');

console.log('🚀 Running Complete Test Suite for OurFakeStore\n');
console.log('═'.repeat(60));

let allTestsPassed = true;

// Run Jest component tests
console.log('\n📦 COMPONENT TESTS (Jest + React Testing Library)');
console.log('─'.repeat(60));
try {
    const jestOutput = execSync('npm run test:components', {
        encoding: 'utf-8'
    });

    // Extract and display Jest summary
    const jestLines = jestOutput.split('\n');
    const summaryStart = jestLines.findIndex(line => line.includes('Test Suites:'));
    if (summaryStart >= 0) {
        const summaryLines = jestLines.slice(summaryStart, summaryStart + 3);
        console.log(summaryLines.join('\n'));
    }
    console.log('✅ Jest component tests completed successfully');
} catch (error) {
    console.log('❌ Jest tests failed');
    console.log(error.stdout);
    allTestsPassed = false;
}

// Run Playwright E2E tests  
console.log('\n🎭 END-TO-END TESTS (Playwright + Electron)');
console.log('─'.repeat(60));
try {
    const playwrightOutput = execSync('npm run test', {
        encoding: 'utf-8'
    });

    // Extract and display Playwright summary
    const playwrightLines = playwrightOutput.split('\n');
    const testCountLine = playwrightLines.find(line => line.includes('passed'));
    if (testCountLine) {
        console.log(testCountLine.trim());
    }
    console.log('✅ Playwright E2E tests completed successfully');
} catch (error) {
    console.log('❌ Playwright tests failed');
    console.log(error.stdout);
    allTestsPassed = false;
}

// Summary
console.log('\n' + '═'.repeat(60));
console.log('📊 TEST SUMMARY');
console.log('═'.repeat(60));

if (allTestsPassed) {
    console.log('🎉 ALL TESTS PASSED!');
    console.log('\n✨ Component logic: Verified (7 Jest tests)');
    console.log('✨ End-to-end flow: Verified (4 Playwright tests)');
    console.log('✨ Ready for deployment! 🚀');
    process.exit(0);
} else {
    console.log('💥 SOME TESTS FAILED!');
    console.log('\n🔧 Please fix failing tests before proceeding');
    process.exit(1);
}