// Generated by Copilot
// Tests for Header React component - Story 1: Basic Header Component
import '@testing-library/jest-dom';
import React from 'react';
import { render } from '@testing-library/react';
import { Header } from '../../src/components/Header';

describe('Header Component - Story 1', () => {

    describe('Test 1.1: Header component renders without crashing', () => {
        test('renders Header component without throwing errors', () => {
            // Given: A Header component exists
            // When: I render the Header component
            // Then: The component renders without throwing errors

            expect(() => {
                render(<Header />);
            }).not.toThrow();
        });
    });

});
