// Generated by Copilot
// Unit tests for MockStoreAdapter - Story 1.5: API Mocking
import { MockStoreAdapter } from '../../src/fake-store-api-client';
import { testProducts } from '../../tests/productsData';

describe('MockStoreAdapter - Story 1.5', () => {
    describe('Test 1.5.1: MockStoreAdapter returns test data correctly', () => {
        test('returns testProducts in AxiosResponse format', async () => {
            // Given: A MockStoreAdapter exists
            // When: I call getProducts()
            // Then: It should return testProducts wrapped in AxiosResponse format

            const mockAdapter = new MockStoreAdapter();
            const response = await mockAdapter.getProducts();

            // Verify response structure
            expect(response.status).toBe(200);
            expect(response.statusText).toBe("OK");
            expect(response.data).toEqual(testProducts);
            expect(response.data).toHaveLength(20);

            // Verify first product structure matches expected format
            const firstProduct = response.data[0];
            expect(firstProduct).toHaveProperty('id');
            expect(firstProduct).toHaveProperty('title');
            expect(firstProduct).toHaveProperty('price');
            expect(firstProduct).toHaveProperty('category');
            expect(firstProduct).toHaveProperty('description');
            expect(firstProduct).toHaveProperty('image');
            expect(firstProduct).toHaveProperty('rating');
        });
    });
});
