
import React, { useState, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import { eventNames } from 'process';
import { Product } from './domain/Product';
import { SimpleProductList } from './components/SimpleProductList';
import { Header } from './components/Header';
import './index.css';

console.log('👋 This message is being logged by "renderer.js", included via webpack');

const app = document.createElement("div");
app.innerHTML = `<ul id="product-list"></ul>`;
document.body.appendChild(app);

const productList = document.getElementById("product-list");

// Generated by Copilot
// Feature flag to toggle between vanilla DOM and React implementation
const USE_REACT_PRODUCTLIST = true;

// State for React component
let reactProducts: Product[] | Error | null = null;
let reactRootInstance: any = null;

// Function to update React component
const updateReactApp = (productsOrError: Product[] | Error | null) => {
  if (mainAppRoot && USE_REACT_PRODUCTLIST) {
    mainAppRoot.render(<App products={productsOrError} />);
  }
};

window.storeAPI.loadProducts((event, productsOrError) => {
  console.log(`loading products: ${productsOrError}`);

  if (USE_REACT_PRODUCTLIST) {
    // React implementation with full app
    updateReactApp(productsOrError);
  } else {
    // Vanilla DOM implementation (existing)
    if (productsOrError instanceof Error) {
      productList!.innerHTML = "<li>Failed to fetch products</li>";
      return;
    } else {
      const products = productsOrError as Product[];
      if (products.length > 0) {
        productList!.innerHTML = products
          .map((product) => `<li>${product.title} - $${product.price}</li>`)
          .join("");
      } else {
        productList!.innerHTML = "<li>No products available. Please come back soon!</li>";
      }
    }
  }
});

// Generated by Copilot
// Main App component - maintaining backward compatibility with existing DOM structure
const App: React.FC<{ products: Product[] | Error | null }> = ({ products }) => {
  return (
    <div>
      <Header />
      <ul id="product-list">
        <SimpleProductList productsOrError={products} />
      </ul>
    </div>
  );
};

// Initialize React app root
let mainAppRoot: any = null;
if (USE_REACT_PRODUCTLIST) {
  // Replace the existing DOM structure with React, maintaining same structure for tests
  const existingApp = document.querySelector('div'); // Find the existing app div
  if (existingApp) {
    mainAppRoot = createRoot(existingApp);
    mainAppRoot.render(<App products={null} />);
  }
} else {
  // Render React app in a hidden container to avoid test interference (legacy)
  const reactContainer = document.createElement("div");
  reactContainer.id = "react-status";
  reactContainer.style.display = "none";
  document.body.appendChild(reactContainer);
  const root = createRoot(reactContainer);
  root.render(<div style={{ display: 'none' }}>React integrated ✓</div>);
}

