
import React, { useState, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import { eventNames } from 'process';
import { Product } from './domain/Product';
import { ProductList } from './components/ProductList';
import { Header } from './components/Header';
import './index.css';

console.log('👋 This message is being logged by "renderer.js", included via webpack');

const app = document.createElement("div");
app.innerHTML = `<div id="product-list"></div>`;
document.body.appendChild(app);

const productList = document.getElementById("product-list");

// Generated by Copilot
// Feature flag to toggle between vanilla DOM and React implementation
const USE_REACT_PRODUCTLIST = true;
const USE_REACT_HEADER = true;

// State for React component
let reactProducts: Product[] | Error | null = null;
let reactRootInstance: any = null;
let reactHeaderInstance: any = null;

// Function to update React component
const updateReactProductList = (productsOrError: Product[] | Error) => {
  if (reactRootInstance && USE_REACT_PRODUCTLIST) {
    reactProducts = productsOrError;

    // Convert to ProductList component format
    if (productsOrError instanceof Error) {
      reactRootInstance.render(<ProductList products={[]} isLoading={false} error={productsOrError} />);
    } else {
      reactRootInstance.render(<ProductList products={productsOrError} isLoading={false} error={null} />);
    }
  }
};

window.storeAPI.loadProducts((event, productsOrError) => {
  console.log(`loading products: ${productsOrError}`);

  if (USE_REACT_PRODUCTLIST) {
    // React implementation
    updateReactProductList(productsOrError);
  } else {
    // Vanilla DOM implementation (existing)
    if (productsOrError instanceof Error) {
      productList!.innerHTML = "<li>Failed to fetch products</li>";
      return;
    } else {
      const products = productsOrError as Product[];
      if (products.length > 0) {
        productList!.innerHTML = products
          .map((product) => `<li>${product.title} - $${product.price}</li>`)
          .join("");
      } else {
        productList!.innerHTML = "<li>No products available. Please come back soon!</li>";
      }
    }
  }
});

// Generated by Copilot
// Simple App component to test React integration - hidden during tests
const App: React.FC = () => {
  return <div style={{ display: 'none' }}>React integrated ✓</div>;
};

// Render React app in a hidden container to avoid test interference
const reactContainer = document.createElement("div");
reactContainer.id = "react-status";
reactContainer.style.display = "none";
document.body.appendChild(reactContainer);
const root = createRoot(reactContainer);
root.render(<App />);

// Initialize React ProductList root if feature flag is enabled
if (USE_REACT_PRODUCTLIST) {
  const productListContainer = document.getElementById("product-list");
  if (productListContainer) {
    reactRootInstance = createRoot(productListContainer);
  }
}

// Initialize React Header if feature flag is enabled
if (USE_REACT_HEADER) {
  const headerContainer = document.createElement("div");
  headerContainer.id = "react-header";
  document.body.insertBefore(headerContainer, document.body.firstChild);
  reactHeaderInstance = createRoot(headerContainer);
  reactHeaderInstance.render(<Header />);
}

