// Generated by Copilot
// Jest setup file for React Testing Library
import '@testing-library/jest-dom';

// Explicitly declare jest-dom types for TypeScript
declare global {
    namespace jest {
        interface Matchers<R> {
            toBeInTheDocument(): R;
            toHaveClass(className: string): R;
            toHaveAttribute(attr: string, value?: string): R;
            toHaveTextContent(text: string): R;
            toContainElement(element: HTMLElement | null): R;
        }
    }
}
